name: Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: ['bug']
assignees:
  - xfqwdsj
body:
  - type: markdown
    attributes:
      value: |
        *(For Chinese users)* **Issue标题请使用英文，内容可为中文**
  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: Clearly describe the bug.
      placeholder: e.g., App crashes on launch
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: e.g., 1. Open the app 2. Tap on 'Hide USB debugging' 3. Observe crash
    validations:
      required: true
  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: e.g., The switch state changed without crashing
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach screenshots to help explain the issue.
      placeholder: Paste your screenshot here.
      value: |
        <details><summary>Screenshots</summary>
        <!-- Paste your screenshots below -->

        </details>
  - type: input
    id: smartphone_info
    attributes:
      label: Smartphone Details
      description: Provide device and OS details.
      placeholder: |
        e.g., Device: Xiaomi 14, OS: Xiaomi Hyper OS 1.0.23.12.4.DEV; Android 14
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Provide logs to help diagnose the issue.
      placeholder: Paste your logs here.
      value: |
        <!-- Option 1: Paste the log file below -->


        <!-- Option 2: Use the following format for log text -->
        <details><summary>Logs</summary>

        <!-- Paste your log text in the code block below -->
        ```

        ```

        </details>
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant information.
      placeholder: e.g., Related issues
